// packages/react/src/Toolbar.tsx
import React from "react";
import type { EditorCommand, ToolbarItem } from "pd-editor-core";
import { getDefaultToolbarItems } from "pd-editor-core";

export interface ToolbarProps {
  /** Custom toolbar items, defaults to standard set */
  items?: ToolbarItem[];
  /** Command handler */
  onCommand: (command: EditorCommand | string) => void;
  /** Theme for styling */
  theme?: "light" | "dark";
}

/**
 * Standalone React toolbar component.
 * Use with useMarkdownEditor hook for custom layouts.
 */
export const Toolbar: React.FC<ToolbarProps> = ({
  items,
  onCommand,
  theme = "light",
}) => {
  const toolbarItems = items ?? getDefaultToolbarItems();
  const isDark = theme === "dark";

  return (
    <div
      style={{
        display: "flex",
        alignItems: "center",
        gap: "2px",
        padding: "6px 8px",
        borderBottom: `1px solid ${isDark ? "#30363d" : "#d1d9e0"}`,
        backgroundColor: isDark ? "#161b22" : "#f6f8fa",
        flexWrap: "wrap",
      }}
    >
      {toolbarItems.map((item, i) => {
        if (item.divider) {
          return (
            <div
              key={`divider-${i}`}
              style={{
                width: "1px",
                height: "20px",
                backgroundColor: isDark ? "#30363d" : "#d1d9e0",
                margin: "0 4px",
              }}
            />
          );
        }

        return (
          <button
            key={item.command}
            type="button"
            title={item.shortcut ? `${item.label} (${item.shortcut})` : item.label}
            aria-label={item.label}
            onClick={(e) => {
              e.preventDefault();
              if (item.onClick) item.onClick();
              else onCommand(item.command);
            }}
            style={{
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              width: "28px",
              height: "28px",
              border: "none",
              borderRadius: "4px",
              backgroundColor: "transparent",
              color: isDark ? "#8b949e" : "#636c76",
              cursor: "pointer",
              padding: "0",
              transition: "all 0.15s ease",
            }}
            dangerouslySetInnerHTML={{ __html: item.icon }}
          />
        );
      })}
    </div>
  );
};

// packages/vue/src/Toolbar.tsx
import { defineComponent } from "vue";
import { getDefaultToolbarItems } from "pd-editor-core";
import type { ToolbarItem } from "pd-editor-core";
import type { PropType, VNode, VNodeChild } from "vue";

type JsxRenderable = (props: Record<string, unknown> & { children?: VNodeChild }) => VNode;

export const Toolbar = defineComponent({
  name: "EditorToolbar",
  props: {
    items: { type: Array as PropType<ToolbarItem[]>, default: undefined },
    theme: { type: String as PropType<"light" | "dark">, default: "light" },
  },
  emits: ["command"],
  setup(props, { emit }) {
    return () => {
      const toolbarItems = props.items ?? getDefaultToolbarItems();
      const isDark = props.theme === "dark";
      const Div = "div" as unknown as JsxRenderable;
      const Button = "button" as unknown as JsxRenderable;

      return (
        <Div
          style={{
            display: "flex",
            alignItems: "center",
            gap: "2px",
            padding: "6px 8px",
            borderBottom: `1px solid ${isDark ? "#30363d" : "#d1d9e0"}`,
            backgroundColor: isDark ? "#161b22" : "#f6f8fa",
            flexWrap: "wrap",
          }}
        >
          {toolbarItems.map((item, i) => {
            if (item.divider) {
              return (
                <Div
                  key={`divider-${i}`}
                  style={{
                    width: "1px",
                    height: "20px",
                    backgroundColor: isDark ? "#30363d" : "#d1d9e0",
                    margin: "0 4px",
                  }}
                />
              );
            }

            return (
              <Button
                key={item.command}
                type="button"
                title={item.shortcut ? `${item.label} (${item.shortcut})` : item.label}
                aria-label={item.label}
                innerHTML={item.icon}
                onClick={(event: Event) => {
                  event.preventDefault();
                  if (item.onClick) item.onClick();
                  else emit("command", item.command);
                }}
                style={{
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  width: "28px",
                  height: "28px",
                  border: "none",
                  borderRadius: "4px",
                  backgroundColor: "transparent",
                  color: isDark ? "#8b949e" : "#636c76",
                  cursor: "pointer",
                  padding: "0",
                }}
              />
            );
          })}
        </Div>
      );
    };
  },
});
